[package]
name = "rsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"
num = "0.4.3"
num-bigint = "0.4.5"
num-integer = "0.1.46"
num-prime = "0.4.4"
rand = "0.8.5"
